name: Workflow ArgoCD

on:
  workflow_call:
    secrets:
      docker_username:
        required: true

jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Update Kubernetes Deployment manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.docker_username }}/nextjs-gitops:${{ github.sha }}|" k8s/deployment.yml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
